### PR TITLE
added web app folder and docs folder for github pages

### PR DESCRIPTION
**Pull request by 20chix**
Hi 

I've added the web app folder under eagleeye_web

Also added docs folder which contains the first draft of the web app, which should be added in the repo settings for github pages, so we can see it from the repo link

Let me know if you don't understand part's of the project I've created

### CODE REVIEW

**Comment by ThoughtfulDev** [comment]
Hi,
i have cloned your fork.
Here are a few suggestions:
1. Can you merge the gitignore from the web folder to the original one in the root directory?
2. can you rename eagleeye_web to just web?
3. Please remove docs/dist. What is this for? its just a npm run build right? (cause it looks the same as npm run serve).

Finally: Nice jobs looks good so far.
Regarding the backend: You can already generate a json report using --json <file> flag which you can then parse and display in vue i guess. 
There is a easy way to hide the firefox while running so that shouldnt be the problem but the server still needed xorg since firefox is still not headless (just not shown that way).

I would only merge this pull request after its fully finished since i dont want to merge it right now if its not finished. You can keep me updated if you want. :)

**Comment by 20chix** [comment]
Hi,

1. Sure
2. Sure
3. Docs folder is used by GitHub pages to host the web app. If you don't want the docs folder we can find an alternative for hosting no problems

This pr is only for the front end

I don't have a backend yet,  was thinking to use go or node for that not sure. 

Any idea on where we can host backend and frontend?

Do you mean you would only merge with a working backend and frontend?

**Comment by ThoughtfulDev** [comment]
I dont really want to host that on github docs. I mean if you want to host it on github docs then this should just really be the frontend and you would need a seperate api server somewhere.

Frontend: server or github docs (its free right haha)
Backend: has to be a seperate server (can be selfghosted). Maybe a Python API written in Flask which just runs eagle eye (with the --json option) and parses the file if the job has finished? The flask API would of course also need a queue with uid of the jobs to not get confused.

You can if you want create a simple overview of the plan. For the Backend API i would rather have a seperate repository.

I might also want a seperate repository just for the frontend + backend since it dont want this to get mixed up uin the actual eagle eye program you know? 

The web version should be a seperate component and not a glued in piece.

**Comment by 20chix** [comment]
True, i think it should be in a separate repository too.

I'll try to get it working locally, but i'm not sure if I'm going to host it since most of the provider out there charge based on the use of the server.

**Pull request closed without merging**
